### ISSUE TITLE
Way to work with an object that already exists

### ISSUE THREAD

**Issue by reisraff** [LinioIT/input#19]
Is there a way to way to work with an object that already exists?

or to do something like:

```php
$user = $repository->findOneById($id);

$input = new UpdateUserHandler(); // link the $user here
$input->bind($request->request->all());

if (!$input->isValid()) {
    // error
}

// instead of do this:
// $data = $input->getData('user');
// do this:
$service->update($user);
```

**Comment by klaussilveira** [comment]
Because input is not just an object hydrator, but a heavily opinionated tool for input handling. It's a leaky abstraction that serves it's purpose on specific cases. 

In the example provided, though, the user object should be created using a transformer and your repository is a direct dependency of that transformer. You validate the input, which is an integer, to create a specific object.

**Comment by reisraff** [comment]
I did imagine that, so I tried to do it, but I just get to transform with this path

https://github.com/LinioIT/input/pull/18

Can you take a look at this?

**Comment by klaussilveira** [comment]
You are doing it wrong: you don't transform an object into an object, you transform a scalar into an object. In your specific case, an int. Take a look at the built-in DateTime transformer for more info.

**Comment by reisraff** [comment]
Okay I got your point, but in your example, if I want for example in the same handler set for the transformed datetime one different timezone?

How it would be?

**Comment by klaussilveira** [comment]
You create a custom type for it.
