### ISSUE TITLE
Constraints are overriding type in validation

### ISSUE THREAD

**Issue by igordrnobrega** [LinioIT/input#21]
Creating an input with type and contraints defined It fails to assert that the type is correct.

```php
public function testOverride()
{
    $input = [
        'price' => 'igor'
    ];

    $inputHandler = new TestConstraintOverrideType();
    $inputHandler->bind($input);
    $this->assertFalse($inputHandler->isValid());
}
 
 class TestConstraintOverrideType extends InputHandler
 {
     public function define()
     {
         $this->add('price', 'int', [
             'required' => true,
             'constraints' => [new Range(0)]
         ]);
     }
 }
```

**Comment by igordrnobrega** [comment]
https://github.com/igordrnobrega/input/commit/e04117a875c7fb2a56e752fbe55217d9ab81a8bc

**Comment by igordrnobrega** [comment]
Creating an input with type and contraints defined It fails to assert that the type is correct

**Comment by nesl247** [comment]
The issue is here: https://github.com/LinioIT/input/blob/master/src/Node/BaseNode.php#L68 and https://github.com/LinioIT/input/blob/master/src/Node/BaseNode.php#L161.

The issue is that if the configuration has constraints, it calls `setContraints` which overrides what is added in the node's constructor.
